import { Fragment } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import { Footer, Header, Main } from "../components";

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Search your jobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main styles={[styles.main]}>
        <text>Main</text>
      </Main>

      <Footer />
    </Fragment>
  );
};

export default Home;
